// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAE66mYY0iz701Fa4w4tmWwI3cGnVArgQY",
    authDomain: "app-final-86528.firebaseapp.com",
    projectId: "app-final-86528",
    storageBucket: "app-final-86528.appspot.com",
    messagingSenderId: "937488615458",
    appId: "1:937488615458:web:a6bef5f947efb91de9627b"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyAE66mYY0iz701Fa4w4tmWwI3cGnVArgQY",
    authDomain: "app-final-86528.firebaseapp.com",
    projectId: "app-final-86528",
    storageBucket: "app-final-86528.appspot.com",
    messagingSenderId: "937488615458",
    appId: "1:937488615458:android:41b019c1bddde9c2e9627b"
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyAE66mYY0iz701Fa4w4tmWwI3cGnVArgQY",
    authDomain: "app-final-86528.firebaseapp.com",
    projectId: "app-final-86528",
    storageBucket: "app-final-86528.appspot.com",
    messagingSenderId: "937488615458",
    appId: "1:937488615458:ios:ede68a0e2dfc6306e9627b"
  );
}